#!/bin/bash

# These need to be configured for the desired environment
BUILDROOTVER=2011.05
KERNELVER=2.6.39.4
UNIONFSVER=2.5.10
PACKAGES=heyu


# Helper Vars
TAGMAJOR=`cat .tag.major`
TAGMINOR=`cat .tag.minor`
BUILD=`cat .build`
TAG=v${TAGMAJOR}.${TAGMINOR}
ROOTDIR=${PWD}
UNIONFSPATCH=unionfs-${UNIONFSVER}_for_${KERNELVER}.diff
BUILDROOTSRC=${ROOTDIR}/src/buildroot-${BUILDROOTVER}.tar.bz2
IMAGES=${ROOTDIR}/buildroot/output/images
TMPDIR=${ROOTDIR}/tmp
SRCDIR=${ROOTDIR}/src
CFGDIR=${ROOTDIR}/config
PKGDIR=${ROOTDIR}/custom

printconf()
{
    echo -e "\nALIXDEV"
    echo -e "------------------------\n"
    echo Build:     ${VERSION}
    echo Tag:       ${TAG}
    echo Buildroot: ${BUILDROOTVER}
    echo Kernel:    ${KERNELVER}
    echo UnionFS:   ${UNIONFSVER}
    echo -e "\n"
}

checklink()
{
	if [ ! -h ${ROOTDIR}/buildroot ]
	then
		echo "Error, ${ROOTDIR}/buildroot link does not exist. Run $0 unpack"
		exit 1
	fi
}

mklink()
{
	ln -s buildroot-${BUILDROOTVER} buildroot
}

makecf()
{
    mkdir -p ${TMPDIR} > /dev/null
    qemu-img create -f raw ${TMPDIR}/cf.img 32M
    losetup /dev/loop0 ${TMPDIR}/cf.img
    echo -e  "n\np\n1\n1\n\nt\n6\na\n1\nw\n" | fdisk /dev/loop0
    losetup -d /dev/loop0
    losetup -o 512 /dev/loop0 ${TMPDIR}/cf.img
    mkfs -t msdos /dev/loop0
    syslinux --install /dev/loop0
    mkdir ${TMPDIR}/mnt
    sudo mount -t msdos /dev/loop0 ${TMPDIR}/mnt
    sudo cp cf/* ${TMPDIR}/mnt/
    sudo umount /dev/loop0
    losetup -d /dev/loop0
    rm -rf ${TMPDIR}/mnt/
}

makefw()
{
    mkdir -p ${TMPDIR}/firmware
    if [ -f ${IMAGES}/bzImage ] && [ -f ${IMAGES}/rootfs.initramfs ]
    then
        cp ${IMAGES}/bzImage ${IMAGES}/rootfs.initramfs ${TMPDIR}/firmware
        cp ${ROOTDIR}/cf/syslinux.cfg ${TMPDIR}/firmware
        cd ${TMPDIR}/firmware
        tar cvfz ${ROOTDIR}/alixdev-bin-0.${VERSION}.tgz *
    else
        echo "Error, missing source file"
        exit 1
    fi
}

case $1 in
    version)
        printconf
        ;;
	get)
        	if [ ! -d ${SRCDIR} ]
        	then
            		mkdir ${SRCDIR}
        	fi
		if [ ! -f ${SRCDIR}/buildroot-${BUILDROOTVER}.tar.bz2 ]
		then
			cd ${SRCDIR}
			wget http://buildroot.uclibc.org/downloads/buildroot-${BUILDROOTVER}.tar.bz2
		fi
            cd ${SRCDIR}
        	wget http://download.filesystems.org/unionfs/unionfs-2.x-latest/${UNIONFSPATCH}.gz
		;;
	unpack)
		if [ ! -f $BUILDROOTSRC ]
		then
			$0 get
		fi
		tar xvfj ${SRCDIR}/buildroot-${BUILDROOTVER}.tar.bz2
		mklink
        gunzip ${SRCDIR}/${UNIONFSPATCH}.gz
		cp -v ${CFGDIR}/buildroot-${BUILDROOTVER}.config ${ROOTDIR}/buildroot/.config
        for pkg in ${PACKAGES}
        do
            cp -Rv ${PKGDIR}/${pkg} ${ROOTDIR}/buildroot/package
        done
		;;
	backup)
		cp -v ${ROOTDIR}/buildroot/.config ${ROOTDIR}/config/buildroot${BUILDROOTVER}.config
		cp -v ${ROOTDIR}/buildroot/output/build/linux-${KERNELVER}/.config ${ROOTDIR}/config/linux-${KERNELVER}-alix-unionfs
		;;
	build)
		let VERSION+=1
		echo -e "\nALIXDEV Build ${VERSION}\n" > ${ROOTDIR}/skeleton/etc/issue
        cp ${ROOTDIR}/skeleton/etc/issue ${ROOTDIR}/buildroot/output/target/etc/
		echo ${VERSION} > buildver
        if [ ! -f ${ROOTDIR}/buildroot/.config ]
        then
            echo "Config not found, will copy..."
            $0 cpconfig
        fi
		(cd buildroot ; make all | tee ../build.log)
		;;
    makefw)
        makefw
        ;;
	runvm)
        if [ ! -f vm/cf.img ]
        then
            makecf
        fi
		qemu -cpu pentium -kernel ${IMAGES}/bzImage -initrd ${IMAGES}/rootfs.initramfs -serial stdio -net nic,vlan=1 -net user,vlan=1 -hda ${ROOTDIR}/vm/cf.img
		;;
	*)
		echo "Error, unknown function $1"
		;;
esac


